#! /bin/bash

### BEGIN INIT INFO
## Provides:          supervisord
## Required-Start:    
## Required-Stop:     
## Should-Start:      
## Should-Stop:       
## Default-Start:     2 3 4 5
## Default-Stop:      0 1 6
## Short-Description: Start and stop the supervisord process control  database server daemon
## Description:       Control supervisord 
### END INIT INFO

SUPERVISORD=/usr/local/bin/supervisord
SUPERVISORCTL=/usr/local/bin/supervisorctl
SUPERVISOR_CONF=/etc/supervisord.conf

case $1 in
start)
        echo -n "Starting supervisord: "
        $SUPERVISORD -c $SUPERVISOR_CONF
        echo
        ;;
stop)
        echo -n "Stopping supervisord: "
        $SUPERVISORCTL -c $SUPERVISOR_CONF shutdown
        echo
        ;;
restart)
        echo -n "Stopping supervisord: "
        $SUPERVISORCTL -c $SUPERVISOR_CONF shutdown
        echo
        sleep 1
        echo -n "Starting supervisord: "
        $SUPERVISORD -c $SUPERVISOR_CONF
        echo
        ;;
esac
